-- JALANKAN DI SUPABASE SQL EDITOR
ALTER TABLE users ADD COLUMN IF NOT EXISTS alamat TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS no_hp_display TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS footer_struk TEXT DEFAULT 'Terima kasih! 🙏';
ALTER TABLE users ADD COLUMN IF NOT EXISTS ukuran_struk TEXT DEFAULT '58';
